runtime: python39

entrypoint: gunicorn -b :$PORT src.app:app

env_variables:
  PROJECT_ID: "greenhouse-alerter"
  GREENHOUSE_SENSOR_ID: "309810.5733909643605740363"
  SAMPLE_LIMIT: 20
  TEMPERATURE_HIGH_TRIGGER: 100
  TEMPERATURE_LOW_TRIGGER: 90