runtime: python39

entrypoint: gunicorn -b :$PORT src.app:app

env_variables:
  PROJECT_ID: "greenhouse-alerter"
  GREENHOUSE_SENSOR_ID: "309810.5733909643605740363"
  SAMPLE_LIMIT: 20
  CHECK_CYCLE_TIME: 2
  TEMPERATURE_TRIGGER: 110