name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        service_account: 'greenhouse-alerter@appspot.gserviceaccount.com'
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'
        project_id: greenhouse-alerter

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --quiet
