name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python3 -m unittest discover -v

  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        service_account: 'greenhouse-alerter@appspot.gserviceaccount.com'
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'
        project_id: greenhouse-alerter

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Plan
      run: |
        export TF_VAR_project_id=$TF_VAR_PROJECT_ID
        terraform plan
      env:
        TF_VAR_PROJECT_ID: '${{ secrets.TF_VAR_PROJECT_ID }}'
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform

    - name: Deploy to App Engine
      run: |
        gcloud app deploy app.yaml --quiet
